---
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - default
  
  courses:
    image: courses_app
    build:
      context: .
    container_name: courses_app
    env_file:
      - .env.prod
    # ports:
    #   - "7777:8000"
    # command: ["/app/docker/app.sh"]
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - ~/prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - default

networks:
  default:
    name: bot_network
    external: true
