"""added relation users and courses

Revision ID: 21801922186f
Revises: dbbcdc9b345c
Create Date: 2025-09-11 14:23:03.335834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21801922186f'
down_revision: Union[str, Sequence[str], None] = 'dbbcdc9b345c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_lectors',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.drop_constraint(op.f('course_teacher_id_fkey'), 'course', type_='foreignkey')
    op.drop_column('course', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('course_teacher_id_fkey'), 'course', 'users', ['teacher_id'], ['id'])
    op.drop_table('course_lectors')
    # ### end Alembic commands ###
